#pragma once
#ifndef GUID_A2759F8254E74760A21048340607EAB4
#define GUID_A2759F8254E74760A21048340607EAB4

#include "window_message.h"

namespace image_viewer {

//! コントロールID (0, 0x6FFF]
/*!	100か101から使うのが慣例
	WM_CREATE,WM_CLOSE,WM_COMMAND(111)とかぶらないようにする
	ループ回したりするのでenum classは使わない。
	メニューはこのID順に並ぶ
*/
enum class ID : int {
	UNDEFINED,
	LAST_PATH,
	PROFILE_ENABLE,
	CONTROL_USEDEFAULT,
	LOADER_RANGE,
	LOADER_MEMORY_CAP,
	LOADER_IMAGE_LOADED,
	LIST_EMPTY,
	CONFIRM_DELETE,

	WINDOW_REMINDER,
	WINDOW_ZOOMING,
	WINDOW_STYLE,
	WINDOW_POSITION,
	WINDOW_LEFT,
	WINDOW_TOP,
	WINDOW_RIGHT,
	WINDOW_BOTTOM,
	WINDOW_MAXIMIZE,

	IDM_USER = 150,

	COMMAND_BEGIN = 200,
	GRIP_IMAGE,
	UNGRIP_IMAGE,
	LIST_REMOVE,
	FILE_QUICK_DELETE,

	MENU_BEGIN,

	FILE_PREVIOUS,
	FILE_NEXT,
	FILE_FIRST,
	FILE_LAST,
	FILE_RELOAD,
	FILE_DELETE,
	USE_PROFILE,
	SCREEN_TOGGLE,

	VIEW_BEGIN,
	VIEW_POPUP,
	VIEW_FILENAME,
	VIEW_LIST,
	VIEW_CENTER,
	VIEW_UPSCALE,
	VIEW_DOWNSCALE,
	VIEW_END,

	SORT_BEGIN,
	SORT_GREATER_WRITE,
	SORT_LESSER_WRITE,
	SORT_GREATER_CREATION,
	SORT_LESSER_CREATION,
	SORT_GREATER_ACCESS,
	SORT_LESSER_ACCESS,
	SORT_END,

	SHOW_PROPERTY,
	WINDOW_CLOSE,

	MENU_END,

	COMMAND_END,
	IDM_USER_END,		// 終端
}; // enum

} // namespace

#endif